services:
  bot-db:
    image: postgres:16
    environment:
      POSTGRES_DB: vpn_bot
      POSTGRES_USER: vpn_bot
      POSTGRES_PASSWORD: vpn_bot
    ports:
      - "5433:5432"
    volumes:
      - bot_db_data:/var/lib/postgresql/data

volumes:
  bot_db_data:
